[project]
name = "temporal-contract-review"
version = "0.1.0"
description = "Repository for Temporal contract review workflow"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "temporalio>=1.18.2",
]
